### PR TITLE
Update packages in environment.yml

### PR DESCRIPTION
**Pull request by cmspeed**
This PR includes updates to the versions of several dependencies in `environment.yml`. Key updates are to GDAL>=3.6.2 and Python>=3.10, which should solve the issues posed in #26 and #27. These changes required updates to several other package versions, and new libraries `leafmap` and `ipyleaflet` have been added to the environment. Additionally, packages have been migrated to Conda install from pip, with the exception of `gdal-utils` which is only pip installable.

Updated environment has been tested across all notebooks in OPERA_Applications repo successfully. However, additional testing would be helpful to ensure all workflows remain functional.

### CODE REVIEW

**Review by kvenkman — CHANGES_REQUESTED** [review]
Changes look good to me, and this should work with all of the OPERA applications developed thus far. I would change back the name of the environment to `opera_app` before it gets merged.

**Review by kdevlin525 — CHANGES_REQUESTED** [review]
All of the changes work on my end. I did realize though that I installed `imageio` to create gifs, which wasn't in the old `environment.yml` file. I added `imageio=2.31.1` to my clone and rebuilt my environment based on this PR, and everything looks like it is still working with the addition. @cmspeed do you want to see if it works with `ipyleaflet`?

**Comment by cmspeed** [comment]
Added `imageio=2.31.1` to environment.yml and everything builds and runs smoothly. Restored name to `opera_app` and will merge now. Thanks for testing!

**Comment by EJFielding** [comment]
I am still not able to install the environment on my M1 Mac because of the nodejs=14.18.3 not being available, the other part of the issue #26 . The oldest version available on my M1 Mac is 15.8.0.
```
conda search nodejs
Loading channels: done
# Name                       Version           Build  Channel
nodejs                        15.8.0      h3f26200_1  conda-forge
nodejs                       15.10.0      h3f26200_0  conda-forge
...
```

**Comment by cmspeed** [comment]
Sorry for missing the nodejs dependency in the original issue. `environment.yml` is now updated with nodejs==18.16.1. Please give this update a try and see if the `opera_app` conda environment works on your machine. Thanks for reporting the M1 chip related issues – I've got a feeling many others would have run into this snag before too long.

**Comment by EJFielding** [comment]
Thanks! Now the installation completes on my M1 Mac. They stopped selling Intel MacBooks two years ago, and the last Intel Mac Pro a few months ago, so the transition is well underway.

**Pull request merged**
